---
- hosts: all
  remote_user: devops
  become: true
  vars:
    system_owner: clyde@exmaple.com
  tasks:
    - template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
