galaxy_info:
  author: Multiple Authors
  description: A role to install and configure apache for Example, Inc.
  company: Example, Inc.

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker


  min_ansible_version: 2.4


  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
    - apache

#No dependencies
dependencies: []

