---
- name: Remove scheduled cron job
  hosts: webservers
  become: true
  tasks:
    - name: Cron job removed
      cron:
        name: Add date and time to a file
        cron_file: add-date-time
        state: absent
      
